<?xml version="1.0" encoding="UTF-8"?>

<!-- Defino el lenguaje que quiero (gramática)
    Un lenguaje que solo tiene la marca raiz
    y dentro de ella hay varios productos
    añado el sufijo + -->
<!DOCTYPE tienda [
    <!ELEMENT tienda (producto+)>
    <!ELEMENT producto (nombre, descripcion?, stock)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT stock (#PCDATA)>
]>

<!--Ejemplo de uso del lenguaje-->
<!-- Dentro del elemento tienda solo puede haber
     cadenas de texto. Ninguna etiqueta -->
<tienda>
    <producto>
        <nombre>Alhambra II</nombre>
        <descripcion>Placa con FPGA ice40</descripcion>
        <stock>3</stock>
    </producto>
</tienda> 